development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NTUMB_development
  pool: 5
  username: 
  password: ''
  host: localhost
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NTUMB_test
  pool: 5
  username: 
  password: 
  host: localhost
  socket: /var/lib/mysql/mysql.sock

production: 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NTUMB_production
  pool: 5
  username: 
  password:
  host: localhost
  socket: /var/lib/mysql/mysql.sock

